### PR TITLE
Cp 183: change query selector

### PR DESCRIPTION
**Pull request by Hatscat**
* [Specs](https://phantombuster.atlassian.net/browse/CP-183)
* improve setup query selectors to allow DOM changes from the App

### CODE REVIEW

**Comment by stressGC** [comment]
Sorry I won't have the time to test. Please keep in mind the retro compatibility we need on the extension. GL

**Review by Oxygen66 — APPROVED** [review]
LGTM 👍

**Review by Oxygen66 — APPROVED** [review]
LGTM 👍

**Review by RiahiKarim — APPROVED** [review]
LGTM 💯

**Pull request merged**
