### PR TITLE
PHOENIX-502 add .nvmrc file

### PR DESCRIPTION
**Pull request by nasrat-v**
## 📝 What is this PR

-   [Specs](https://phantombuster.atlassian.net/browse/PHOENIX-502)

### CODE REVIEW

**Review by stressGC — APPROVED** [review]
Code LGTM, how did you determine the correct version to use?

**Comment by nasrat-v** [comment]
> Code LGTM, how did you determine the correct version to use?

Starting from `16.x.x` and downgrading to major LTS release until the web-browser extension build without weird warning related to the nodejs version and it worked.

**Comment by nasrat-v** [comment]
We can't keep v15 because odd version are instable release: https://nodejs.org/en/about/releases/
After discussion with @arnauddrain, the version used was 14.14 (like `@types/node` in package.json).
We decided to go with the v14.19.1 (Latest LTS: Fermium), the latest LTS for v14.

**Review by Drax35c2db — APPROVED** [review]
Okay but in the long run the code of this repo should probably be updated to have a node version matching the front: `16.13.0` (https://github.com/phantombuster/pb2-front/blob/master/.nvmrc)

**Pull request merged**
