### PR TITLE
ci: add manifest diff check

### PR DESCRIPTION
**Pull request by Hatscat**

### CODE REVIEW

**Review by Oxygen66 — DISMISSED** [review]
LGTM 👍

**Review by RiahiKarim — COMMENTED** [review]
LGTM 💯 . Shouldn't we revert back the manifest version to `1.1.6.2` before meging?

**Comment by Hatscat** [comment]
> LGTM 💯 . Shouldn't we revert back the manifest version to `1.1.6.2` before merging?
> 
> We could also add a link to the diff comment this [readme warning](https://github.com/phantombuster/web-browser-extension#contributing).

Done 🙂

**Review by RiahiKarim — APPROVED** [review]
LGTM 💯

**Review by Oxygen66 — APPROVED** [review]
LGTM 👍

**Pull request merged**
